title: Data Exploration Blog
baseurl: "/data-exploration-blog/"
# theme: jekyll-theme-minimal
author: write your name
# google_analytics: [Your Google Analytics tracking ID]

theme: minima

collections:
  explorations:
    output: true

header_pages:
  - index.md
  - about.md

minima:
  skin: dark
