title: Data Exploration Blog
baseurl: "/data-exploration-blog"
theme: jekyll-theme-minimal
author: write your name

collections:
  explorations:
    output: true

header_pages:
  - index.md
  - about.md

minima:
  skin: dark
