title: Data Exploration Blog
theme: jekyll-theme-minimal

collections:
  explorations:
    output: true

# # Page tree that defines the navigation structure
# nav:
#   - Home: index.md
#   - Proactive Skills:
#       - Introduction: proactive-skills/introduction-proactive-skills.md
#       - Technical Skills:
#           - Introduction: proactive-skills/technical-skills/introduction-technical-skills.md
#           - Using VS Code: proactive-skills/technical-skills/using-vscode.md
#           - Using Markdown: proactive-skills/technical-skills/using-markdown.md
#           - Using Terminal: proactive-skills/technical-skills/using-terminal.md
#           - Using GitHub: proactive-skills/technical-skills/using-git.md
#           # - Using Docker: proactive-skills/technical-skills/using-docker.md
#           - Python Programming: proactive-skills/technical-skills/python-programming.md
#           - Python Packaging: proactive-skills/technical-skills/python-packages.md
#           - Using GatorGrader: proactive-skills/technical-skills/using-gatorgrader.md
#       - Professional Skills:
#           - Introduction: proactive-skills/professional-skills/introduction-professional-skills.md
#           - Effective Communication: proactive-skills/professional-skills/effective-communication.md
#           - Time Management: proactive-skills/professional-skills/time-management.md
#           - Reading Documentation: proactive-skills/professional-skills/reading-documentation.md
#   - Proactive Community:
#       - Introduction: proactive-community/introduction-proactive-community.md
#       - Technical Community: proactive-community/technical-resources.md
#       - Professional Community: proactive-community/professional-resources.md
#       - Our Community: proactive-community/community-connections.md
#   - Proactive Learning:
#       - Introduction: proactive-learning/introduction-proactive-learning.md
#       - Bloom's Taxonomy: proactive-learning/blooms-taxonomy.md
#       - Assignment Types: proactive-learning/assignment-types.md
#       - Assessment Strategy: proactive-learning/assessment-strategy.md
#   - Data Abstraction:
#       - Introduction: data-abstraction/introduction-data-abstraction.md
#       - Learning Objectives: data-abstraction/learning-objectives-data-abstraction.md
#       - Course Syllabus: data-abstraction/syllabus-data-abstraction.md
#       - Course Schedule: data-abstraction/schedule-data-abstraction.md
#       - Source Code Surveys:
#           - Numerical Data: data-abstraction/source-code-surveys/numerical-data.md
#           - Structured Types: data-abstraction/source-code-surveys/structured-types.md
#           - Debugging Functions: data-abstraction/source-code-surveys/debugging-functions.md
#           - Container Cloning: data-abstraction/source-code-surveys/container-cloning.md
#           - Knapsack Solvers: data-abstraction/source-code-surveys/knapsack-solvers.md
#       - Programming Projects:
#           - Number Comparison: data-abstraction/programming-projects/number-comparison.md
#           - Square Roots: data-abstraction/programming-projects/square-root.md
#           - Matrix Processing: data-abstraction/programming-projects/matrix-processing.md
#       - Engineering Efforts:
#           - Integer Squaring: data-abstraction/engineering-efforts/integer-squaring.md
#           - Primality Testing: data-abstraction/engineering-efforts/primality-testing.md
#           - Intersection Algorithms: data-abstraction/engineering-efforts/intersection-algorithms.md
#           - Fibonacci Algorithms: data-abstraction/engineering-efforts/fibonacci-algorithms.md
#           - Palindrome Checking: data-abstraction/engineering-efforts/palindrome-checking.md
#           - Object Processing: data-abstraction/engineering-efforts/object-processing.md
#           - Sorting Algorithms: data-abstraction/engineering-efforts/sorting-algorithms.md
#           - Containment Checks: data-abstraction/engineering-efforts/containment-checking.md
#   - Discrete Structures:
#       - Introduction: discrete-structures/introduction-discrete-structures.md
#       - Learning Objectives: discrete-structures/learning-objectives-discrete-structures.md
#       - Course Syllabus: discrete-structures/syllabus-discrete-structures.md
#       - Course Schedule: discrete-structures/schedule-discrete-structures.md
#       - Source Code Surveys:
#           - Data Types: discrete-structures/source-code-surveys/data-types.md
#           - Tuple Swapping: discrete-structures/source-code-surveys/tuple-swapping.md
#           - Higher-Order Functions: discrete-structures/source-code-surveys/higher-order-functions.md
#           - Mode Calculation: discrete-structures/source-code-surveys/mode-calculation.md
#           - Using Memoization: discrete-structures/source-code-surveys/using-memoization.md
#           - Representing Objects: discrete-structures/source-code-surveys/representing-objects.md
#       - Programming Projects:
#           - Computing Averages: discrete-structures/programming-projects/average-computation.md
#           - Temperature Conversion: discrete-structures/programming-projects/temperature-conversion.md
#           - Contact Searching: discrete-structures/programming-projects/contact-searching.md
#       - Engineering Efforts:
#           - File Searching: discrete-structures/engineering-efforts/file-searching.md
#           - Quadratic Roots: discrete-structures/engineering-efforts/quadratic-roots.md
#           - Iterative Exponentiation: discrete-structures/engineering-efforts/iterative-exponentiation.md
#           - Data Summarization: discrete-structures/engineering-efforts/data-summarization.md
#           - Data Analysis: discrete-structures/engineering-efforts/data-analysis.md
#           - List Uniquification: discrete-structures/engineering-efforts/list-uniquification.md
#           - Text Processing: discrete-structures/engineering-efforts/text-analysis.md
#           - Collatz Creation: discrete-structures/engineering-efforts/collatz-creation.md
