title: Data Exploration Blog
author: write your name
# google_analytics: [Your Google Analytics tracking ID]

# theme: jekyll-theme-minimal
theme: minima

collections:
  explorations:
    output: true
