title: Data Exploration Blog
baseurl: "/data-exploration-blog"
author: write your name
# google_analytics: [Your Google Analytics tracking ID]

theme: jekyll-theme-minimal

collections:
  explorations:
    output: true

header_pages:
  - index.md
  - about.md
