setup: |
  echo "Done installing project dependencies!"
---

# Reminder for ^^^:
# All commands executed in the setup block are done in a
# one-by-one fashion from the current working directory. This means
# that there is no history associated with running the commands and
# thus multiple commands must be run in a single chain.

# perform checks on a file
- README.md:
    - description: Ensure that the README.md file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in README.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

- _config.yml:
    - description: Ensure that the _config.yml file exists
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers in _config.yml
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

- _explorations/01-hall-of-fame.md:
    - description: Ensure that the _explorations/01-hall-of-fame.md file exists
      check: ConfirmFileExists
    - description: Write minimum of 150 words in _explorations/01-hall-of-fame.md
      check: CountFileWords
      options:
        count: 150
        exact: false
    - description: include at least 2 images in assets/images in 01-hall-of-fame.md
      check: MatchFileFragment
      options:
        fragment: assets/images
        count: 2
        exact: false

- _explorations/02-dot-to-dot-1.md:
    - description: Ensure that the _explorations/02-dot-to-dot-1.md file exists
      check: ConfirmFileExists
    - description: Write minimum of 150 words in _explorations/02-dot-to-dot-1.md
      check: CountFileWords
      options:
        count: 150
        exact: false
    - description: include at least 5 images in assets/images in 02-dot-to-dot-1.md
      check: MatchFileFragment
      options:
        fragment: assets/images
        count: 5
        exact: false

- _explorations/03-dot-to-dot-2.md:
    - description: Ensure that the _explorations/03-dot-to-dot-2.md file exists
      check: ConfirmFileExists
    - description: Write minimum of 150 words in _explorations/03-dot-to-dot-2.md
      check: CountFileWords
      options:
        count: 150
        exact: false
    - description: include at least 4 images in assets/images in 03-dot-to-dot-2.md
      check: MatchFileFragment
      options:
        fragment: assets/images
        count: 4
        exact: false

- _explorations/04-vocal-analysis.md:
    - description: Ensure that the _explorations/04-vocal-analysis.md file exists
      check: ConfirmFileExists
    - description: Write minimum of 250 words in _explorations/04-vocal-analysis.md
      check: CountFileWords
      options:
        count: 250
        exact: false
    - description: include at least 3 images in assets/images in 04-vocal-analysis.md
      check: MatchFileFragment
      options:
        fragment: assets/images
        count: 3
        exact: false

- _explorations/05-google-analytics.md:
    - description: Ensure that the _explorations/05-google-analytics.md file exists
      check: ConfirmFileExists
    - description: Write minimum of 150 words in _explorations/05-google-analytics.md
      check: CountFileWords
      options:
        count: 150
        exact: false

    - description: use correct image name (final-ipynb) in blogpost.md
      check: MatchFileFragment
      options:
        fragment: /assets/images/final-ipynb.
        count: 1
        exact: false
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 2
        exact: false    

  # count number of commits in the GitHub repository
- description: Have a total of at least 5 local commits in repository before pushing
  check: CountCommits
  options:
    count: 5